version: '3'

services:
  db:
    image: 'docker.io/library/postgres:11'
    environment:
      POSTGRES_DB: 'channel-chief'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '1212:5432'
    volumes:
      - 'channel-chief-db:/var/lib/postgresql/data'
    restart: always
    networks:
      - channel-chief-network

networks:
  channel-chief-network:
    driver: bridge

volumes:
  channel-chief-db:
