version: '3'

services:
  channel-chief:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - channel-chief-network
    depends_on:
      - db
  db:
    image: 'docker.io/library/postgres:11'
    environment:
      POSTGRES_DB: 'channel-chief'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'channel-chief-db:/var/lib/postgresql/data'
    restart: always
    networks:
      - channel-chief-network

networks:
  channel-chief-network:
    driver: bridge

volumes:
  channel-chief-db:
